// Add your custom localized strings and then include these string dictionaries in your display templates using the $includeLanguageScript function

$registerResourceDictionary("en-us", {
    "DateFormat": "MMMM d, yyyy",
    "PageContact": "Page Contact:",
    "EditLabel": "Edit",
    "More": "more",
    "results": "Results",
    "SortBy": "Sort",
    "status": "BLGLawyerStatusEn",
    "group": "BLGProNameEn",
    "office": "BLGMergedOfficeEn",
    "title":"BLGTitleEn",
    "speciality": "BLGSpecialityEn",
    "Lang": "en",
    "Print": "Print",
    "SuggestionPartialWord": "Attach wildcard (*) when searching with partial word. i.e. busi*.",
    "RefineResults": "Refine Results",
    "PolicyOwner": "Policy Owner:",
    "EffectiveDate": "Effective Date:",
    "RevisionDate": "Revised Date:",
    "Supercedes": "Supercedes:",
    "ApprovedBy": "Approved By:",
    "ProcedureAuthor": "Author:",
    "LastName": "Last Name",
    "FirstName": "First Name",
    "SearchBy": "List By:",
    "Search": "Search",
    "VirtualMeetingUrl": "Virtual Meeting URL:",
    "VirtualMeetingDialIn": "Virtual Meeting Dial In:",
    "EventLocation": "Location:",
    "EventVenue": "Venue:",
    "EventRoom": "Room:",
    "EventDoorsOpen": "Doors Open:",
    "EventReception": "Reception:",
    "EventVenueUrl": "Venue Url:",
    "EventHost": "Event Host:",
    "EventContact": "Event Contact:",
    "WhoToContact": "Who to contact",
    "rf_RefinementTitle_owstaxIdBLGAdminGroup": "Business Services Group",
    "rf_RefinementTitle_owstaxIdBLGOffice": "Office",
    "rf_RefinementTitle_owstaxIdBLGPracticeGroup": "Practice Groups",
    "rf_RefinementTitle_BLGPublicationDate": "Date",
    "rf_RefinementTitle_owstaxIdBLGNewsType": "News Type",
    "rf_RefinementTitle_BLGIsHighlightOWSBOOL": "Featured Stories",
    "rf_RefinementTitle_BLGIsLeaderCornerOWSBOOL": "Spotlight",
    "rf_RefinementTitle_owstaxIdBLGLinkType": "Link Type",
    "rf_RefinementTitle_owstaxIdBLGAudience": "Link Audience",
    "rf_RefinementTitle_owstaxIdBLGEventType": "Event Type",
    "rf_RefinementTitle_ContentType": "Content Type",
    "rf_RefinementTitle_FileType": "File Type",
    "rf_RefinementTitle_BLGMergedOfficeEn": "Office",
    "rf_RefinementTitle_BLGProNameEn": "Practice Groups",
    "rf_RefinementTitle_BLGPractNameEn": "Focus Groups",
    "rf_RefinementTitle_BLGLawyerStatusEn": "Lawyer Status",
    "rf_RefinementTitle_BLGServNameEn": "Business Service",
    "rf_RefinementTitle_BLGCommitteeEn": "Committee"
});